version: '2'
services:
    jhipster-app:
        image: jhipster
        external_links:
            - jhipster-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the  to boot  tom  the application
        ports:
            - 8080:8080
        networks:
            - hsos_net
    jhipster-mysql:
        extends:
            file: mysql.yml
            service: jhipster-mysql

networks:
  hsos_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1
